### ISSUE TITLE
This library gives me significantly different results compared to Kanjitomo itself

### ISSUE THREAD

**Issue by Darayavaush** [sakarika/kanjitomo-ocr#2]
I'm getting frequent mismatches between the output of this library and the output of Kanjitomo proper, sometimes quite significant. What might be causing this? Is this an outdated version?

Here's an example: 
![image](https://user-images.githubusercontent.com/3651004/80433594-04b1fc00-8900-11ea-95ba-c5ac83cdec44.png)
Kanjitomo correctly makes 想 the top pick for the second character, but for this library it doesn't appear anywhere in the top results.

(I don't think this matters, but I'm using it from Python via PyJnius.)

**Comment by sakarika** [comment]
GUI uses the same library, there should not be any difference. How is the image loaded before passing it to library and is there any image processing involved?

**Comment by sakarika** [comment]
Here's how your image looks with KanjiTomo's build-in debug tester:
![486 20 combined](https://user-images.githubusercontent.com/58656745/80442515-bad41080-8915-11ea-8909-cf30eff24037.png)
![486 62 ocr result 想 3673 0 0 1 1](https://user-images.githubusercontent.com/58656745/80442563-da6b3900-8915-11ea-9299-ecad3d0fcb23.png)
![486 60 ocr original](https://user-images.githubusercontent.com/58656745/80442564-db03cf80-8915-11ea-8dbc-125ec15bf38e.png)
![486 61 ocr reference 想](https://user-images.githubusercontent.com/58656745/80442565-db03cf80-8915-11ea-9fdb-04c4d30cfb8f.png)

So it's a pretty good match. From GUI's standpoint, the correct result should be in the top.

**Comment by Darayavaush** [comment]
Nope, there's no processing, just straight from the source and into the OCR. The same result is returned both when I'm taking a screenshot via Robot and when I'm reading a screenshot from the disk.

Here's a specific minimal example for you (redone in Java just to make sure it's not the fault of the Java-Python bridge):

file.png:
![file](https://user-images.githubusercontent.com/3651004/80493797-893b6380-896e-11ea-9282-767f1709a899.png)

Code:
```
import net.kanjitomo.OCRResults;
import net.kanjitomo.KanjiTomo;
import java.awt.Point;
import java.io.File;
import javax.imageio.ImageIO;
import java.awt.image.BufferedImage;

public class kanjitomo{
        public static void main(String[] args) throws Exception{
			KanjiTomo tomo = new KanjiTomo();
			tomo.loadData();
			File testImageFile = new File("file.png");
			BufferedImage image = ImageIO.read(testImageFile);
			tomo.setTargetImage(image);
			OCRResults results = tomo.runOCR(new Point(30,30));
			System.out.println(results);
	}
}
```

Output:
```
Characters:
妄有妾完弁吏字要宇在冬を
惹値健並酋飢徨処血撻館旭
を玄衣去官舎有杏来史倉布

Locations:
java.awt.Rectangle[x=26,y=23,width=27,height=27]
java.awt.Rectangle[x=26,y=52,width=27,height=28]
java.awt.Rectangle[x=29,y=83,width=20,height=26]

Search string:妄
Words found:26
First word:妄り みだり
```

I've tried changing offsets, crop position and the zoom, and always got the same result (even if the set of kanji in the output changed, the correct one was never present).

**Comment by sakarika** [comment]
I can confirm this example produces wrong results. I have an idea for a fix but it requires some testing. This might take a few days.

**Comment by sakarika** [comment]
I have now updated the library, It should give better results for this image. New jar is at: https://github.com/sakarika/kanjitomo-ocr/blob/master/deploy/KanjiTomoOCR.jar

**Comment by Darayavaush** [comment]
Yep, works better now. Thanks a lot! :)
