### ISSUE TITLE
the OCR overlay it black usually

### ISSUE THREAD

**Issue by intangir** [sakarika/kanjitomo-ocr#4]
when i use the OCR on other windows, it usually pops up a black box over the characters it recognizes

from a screenshot on the page i assume its supposed to only be red boxes, but for me on linuxmint mate it shows black boxes almost always

sometimes it shows boxes within boxes but still obscures the original text

i looked for settings related to either disabling or customizing the ocr overlay window thing but couldn't find any

the main inconvenience of this is i can't confirm the OCR was accurate because the original character is hidden, if i click the window it goes away, but also removes the match from kanjitomo's window

heres an example
occasionally the black box doesn't appear at all, i think the window exists but is not in the foreground so not seen
so alot of inconsistency in its behavior

![Screenshot at 2021-02-02 17-34-41](https://user-images.githubusercontent.com/236488/106676886-5a958d80-657d-11eb-9475-4c4fbb825a41.png)

**Comment by intangir** [comment]
btw this is an absolutely amazing tool, thanks for the work
i use it all the time, its super handy and flexible and impressive, it even gets really odd fonts pretty consistently

**Comment by intangir** [comment]
apparently this bug is with the UI that , not the ocr library..

i don't see source for the UI code though

**Comment by sakarika** [comment]
UI has not been tested on Linux. The OCR library should be platform-independent, but it would need a new GUI to work in Linux.
