### ISSUE TITLE
How does KanjiTomo recognise the area to scan?

### ISSUE THREAD

**Issue by berzi** [sakarika/kanjitomo-ocr#5]
Hi, I have just a little question since I'm working on a similar program to KanjiTomo and am curious: how does KT pick the area close to the pointer to then send to OCR? It doesn't constantly OCR everything near the pointer to see if there's any character match, does it?

**Comment by sakarika** [comment]
Hello. KanjiTomo uses Java's [Robot](https://docs.oracle.com/javase/9/docs/api/java/awt/Robot.html) class to take small screenshots around mouse cursor. This is done when mouse cursor is moved, so in effect OCR is running constantly.
