### ISSUE TITLE
Release source code for GUI?

### ISSUE THREAD

**Issue by sunny-lan** [sakarika/kanjitomo-ocr#6]
I'd like to make a modification to the original GUI for allowing direct adding of words to Anki. Are you willing to release that source code?

Obviously I can rewrite another GUI, but the less work the better :)

**Comment by sakarika** [comment]
I won't be releasing the GUI code. Frankly it's in unmaintainable state and would need a complete rewrite. One reason for releasing the OCR code was so that people with more experience in GUI can write a better one.

**Comment by jaminW55** [comment]
Would you be willing to share this source code? I have been using the program for some time and am interested in how it works. 

I agree with your assessment in regards to the future of OCR tools, but as I have been using programs like this and even older ones, like JGlossator, I am just very interested in the workings of such programs.
